name: pr-check

on:
  pull_request_target:
    branches:
      - main
      - 'releases/*'

jobs:
    deploy:
      environment: Automation test
      runs-on: windows-latest
      steps:
      - name: Checkout from PR branch  
        uses: actions/checkout@v3
        with: 
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
        
        #Using 16.x version as an example
      - name: Set Node.js 16.x for GitHub Action
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: installing node_modules
        run: npm install 
       
      - name: Build GitHub Action
        run: npm run build
                        
      - name: Run Unit Tests
        run: npm run test
          
      # include any workflow/action specific dependencies to execute Functional Tests
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.102
          
      - name: Install dependencies
        working-directory: './Utilities/functional-tests/'
        run: dotnet restore
        
      - name: Build
        working-directory: './Utilities/functional-tests/'
        run: dotnet build --configuration Debug --no-restore
        
      - name: Test
        working-directory: './Utilities/functional-tests/'
        run: dotnet test
        
      - name: 'VSTest Action using functional tests'
        uses: ./                  #picks the current action PR code.
        with:
          testAssembly: 'vstest-functional-test.dll'
          searchFolder: './Utilities/functional-tests/bin/Debug/net6.0/'
